Default: &defaults
  host: "*4" # any IPv4 host
  port: 3000
  approot: "http://localhost:3000"
  copyright: copyright statement - TEST INSTANCE
  #analytics: UA-YOURCODE

Development:
  <<: *defaults

Testing:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  approot: "http://saunahali.funktionaali.com"
  port: 8500
  copyright: Helsingin Akateemisen Löylyttelijät ry
  <<: *defaults
